name: AniBrowser
options:
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    IPHONEOS_DEPLOYMENT_TARGET: '16.0'
    TARGETED_DEVICE_FAMILY: '1,2'
targets:
  AniBrowser:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.anibrowser.ios
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: '0.1.0'
        CURRENT_PROJECT_VERSION: '1'
        CODE_SIGNING_ALLOWED: NO
    scheme:
      gatherCoverageData: false
